###
POST http://localhost:3000/energy HTTP/1.1
content-type: application/json

{
    "name": "Electricity",
    "date": "2021-09-18",
    "score": 10
}

### returns all things posted
GET http://localhost:3000/energy HTTP/1.1


### replace id with electricity id - edits score

PUT http://localhost:3000/energy/6145729b06363b22511d3326 HTTP/1.1
content-type: application/json

{
    "name": "Electricity - test",
    "date":"2021-09-17",
    "score": 25
}

### replace id w id to delete

DELETE http://localhost:3000/energy/6145708607945e223785007c HTTP/1.1


###
POST http://localhost:3000/energy HTTP/1.1
content-type: application/json

{
    "name": "Natural Gas",
    "date": "2021-09-18",
    "score": 22
    
}

###
POST http://localhost:3000/energy HTTP/1.1
content-type: application/json

{
    "name": "Propane",
    "date": "2021-09-18",
    "score": 10
    
}

###
POST http://localhost:3000/energy HTTP/1.1
content-type: application/json

{
    "name": "Fuel Oil",
    "date": "2021-09-18",
    "score": 12
}
